services:
  order-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB_NAME}
    ports:
      - "${ORDER_DB_PORT}:5432"

  payment-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${PAYMENT_DB_NAME}
    ports:
      - "${PAYMENT_DB_PORT}:5432"

  payment-service:
    build:
      context: .
      dockerfile: payment/Dockerfile
    environment:
      - PAYMENT_DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@payment-db:5432/${PAYMENT_DB_NAME}?sslmode=disable
      - PAYMENT_GRPC_PORT=${PAYMENT_GRPC_PORT}
    depends_on:
      - payment-db

  order-service:
    build:
      context: .
      dockerfile: order/Dockerfile
    ports:
      - "8080:8080"
      - "50052:50052"
    environment:
      - ORDER_DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@order-db:5432/${ORDER_DB_NAME}?sslmode=disable
      - ORDER_HTTP_PORT=8080
      - PAYMENT_SERVICE_ADDR=payment-service:50051
    depends_on:
      - order-db
      - payment-service